/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'id' : IDL.Int,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'isVendor' : IDL.Bool,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const VendorProfile = IDL.Record({
  'id' : IDL.Principal,
  'trustedBy' : IDL.Vec(IDL.Principal),
  'menu' : IDL.Vec(MenuItem),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'phone' : IDL.Text,
  'location' : Location,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMenuItem' : IDL.Func([MenuItem], [IDL.Int], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerVendorProfile' : IDL.Func([], [IDL.Opt(VendorProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendorProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(VendorProfile)],
      ['query'],
    ),
  'getVendorProfileCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listVendorProfilesByLocation' : IDL.Func(
      [],
      [IDL.Vec(VendorProfile)],
      ['query'],
    ),
  'removeMenuItem' : IDL.Func([IDL.Int], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMenuItem' : IDL.Func([MenuItem], [], []),
  'upsertVendorProfile' : IDL.Func([VendorProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'id' : IDL.Int,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'isVendor' : IDL.Bool });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const VendorProfile = IDL.Record({
    'id' : IDL.Principal,
    'trustedBy' : IDL.Vec(IDL.Principal),
    'menu' : IDL.Vec(MenuItem),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'phone' : IDL.Text,
    'location' : Location,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMenuItem' : IDL.Func([MenuItem], [IDL.Int], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerVendorProfile' : IDL.Func(
        [],
        [IDL.Opt(VendorProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendorProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(VendorProfile)],
        ['query'],
      ),
    'getVendorProfileCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listVendorProfilesByLocation' : IDL.Func(
        [],
        [IDL.Vec(VendorProfile)],
        ['query'],
      ),
    'removeMenuItem' : IDL.Func([IDL.Int], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMenuItem' : IDL.Func([MenuItem], [], []),
    'upsertVendorProfile' : IDL.Func([VendorProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };